# Storage Safety Settings
storage:
  threshold_percent: 80 # max available system storage percentage when logging will performed if available is less than threshold logging wont happen 
  max_directory_size_mb: 1 # Max directory size to the Logs Directory when logs directory hits the Max size the logger will stop
  max_dir_warning_threshold: 70 # Dirctory size hits threshold% of the Max directory size the logger gives warning Your directory size hits the warning threshold
  max_files: 10 # Number of files in original format in the directory even compression done. when the file goes to 11 the 1 file will be compressed

# Logger Performance & Defaults 
logger:
  directory: "logs11" # Directory Name to the logs directory where the log files stores.
  max_file_size_mb: 0.1 # Max file size to the file it it hits the max size rotation will perform.
  queue_size: 100000 # Queue size how much data queue can hold.
  default_file_type: "csv" # Default file format type. when user not gives the file format for logs it will take default type.
  default_compress: false # Default compression value it tell about the log file will compress or not if it is true if the max_files hits the very first file will compress otherwise compression will not preform
  encoder: false # Default Encoder value it tell about if the user send the normal human readable format for the BIN, TLV.BIN formats to the logger it will convert it into the binary if we put encoder true other wise leave it false

xlsxconfig: # In Excel Format rows will be store in the ram until we save the excel file in that time we won't calucate the file size without file size file rotation not perform. so to perform file rotation based on the no of records in the file.
  rows: 250000 # Default rows count to preform file rotation